apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "slack-pr-reporter.fullname" . }}-config
  labels:
    {{- include "slack-pr-reporter.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.logLevel | quote }}
  EMOJI_MERGED: {{ .Values.defaultEmoji.merged | quote }}
  EMOJI_CLOSED: {{ .Values.defaultEmoji.closed | quote }}
  EMOJI_APPROVED: {{ .Values.defaultEmoji.approved | quote }}
  EMOJI_NEEDS_REVIEW: {{ .Values.defaultEmoji.needsReview | quote }}
  EMOJI_CI_PASSING: {{ .Values.defaultEmoji.ciPassing | quote }}
  EMOJI_CI_FAILING: {{ .Values.defaultEmoji.ciFailing | quote }}
  EMOJI_CI_PENDING: {{ .Values.defaultEmoji.ciPending | quote }}
  EMOJI_HAS_OPEN_COMMENTS: {{ .Values.defaultEmoji.hasOpenComments | quote }}
